import {
  UPDATE_LOGIN_TYPE,
  UPDATE_OTP,
  UPDATE_USER_NAME,
  UPDATE_USER_ACCEPTANCE,
  UPDATE_USER_BMI,
  UPDATE_USER_DOB,
  UPDATE_USER_EMAIL,
  UPDATE_USER_GENDER,
  UPDATE_USER_HEIGHT,
  UPDATE_USER_IMAGE,
  UPDATE_USER_IMAGE_URL,
  UPDATE_USER_MOBILE,
  UPDATE_USER_PASSCODE,
  UPDATE_USER_TEMP_DOB,
  UPDATE_USER_TEMP_HEIGHT,
  UPDATE_USER_TEMP_WEIGHT,
  UPDATE_USER_TOKEN,
  UPDATE_USER_WEIGHT,
} from '../constants/constant';

export const updateUserName = userName => ({
  type: UPDATE_USER_NAME,
  payload: userName,
});
