// convention : variable name and variable variable should be same

// APP-ACTIONS
export const COUNTER_CHANGE = 'COUNTER_CHANGE';
export const IS_TOUCH_ID_ENABLED = 'IS_TOUCH_ID_ENABLED';

// USER-ACTIONS
export const UPDATE_USER_NAME = 'UPDATE_USER_NAME';
export const UPDATE_USER_ACCEPTANCE = 'UPDATE_USER_ACCEPTANCE';
export const UPDATE_LOGIN_TYPE = 'UPDATE_LOGIN_TYPE';
export const UPDATE_USER_MOBILE = 'UPDATE_USER_MOBILE';
export const UPDATE_USER_EMAIL = 'UPDATE_USER_EMAIL';
export const UPDATE_OTP = 'UPDATE_OTP';
export const UPDATE_USER_PASSCODE = 'UPDATE_USER_PASSCODE';
export const UPDATE_USER_GENDER = 'UPDATE_USER_GENDER';
export const UPDATE_USER_DOB = 'UPDATE_USER_DOB';
export const UPDATE_USER_IMAGE = 'UPDATE_USER_IMAGE';
export const UPDATE_USER_TOKEN = 'UPDATE_USER_TOKEN';
export const UPDATE_USER_IMAGE_URL = 'UPDATE_USER_IMAGE_URL';
export const UPDATE_USER_HEIGHT = 'UPDATE_USER_HEIGHT';
export const UPDATE_USER_WEIGHT = 'UPDATE_USER_WEIGHT';
export const UPDATE_USER_TEMP_HEIGHT = 'UPDATE_USER_TEMP_HEIGHT';
export const UPDATE_USER_TEMP_WEIGHT = 'UPDATE_USER_TEMP_WEIGHT';
export const UPDATE_USER_BMI = 'UPDATE_USER_BMI';
export const UPDATE_USER_TEMP_DOB = 'UPDATE_USER_TEMP_DOB';
export const RESET_STATE = 'RESET_STATE';

/* Leader Board  */
export const UPDATE_LEADER_BOARD_DATA = 'UPDATE_LEADER_BOARD_DATA';
